from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
driver=webdriver.Chrome("C:\\Users\\conta\\OneDrive\\Desktop\\jishnu\\chromedriver_win32 (1)\\chromedriver.exe")
driver.get("https://itera-qa.azurewebsites.net/home/automation")
driver.find_element(by=By.ID,value="name").send_keys("jishnu")
driver.find_element(by=By.ID,value="phone").send_keys("9048869977")
driver.find_element(by=By.ID,value="email").send_keys("jishnusreedharan@gmail.com")
driver.find_element(by=By.ID,value="password").send_keys("9048869977jishnu")
driver.find_element(by=By.ID,value="address").send_keys("valliyattumethal,TDY,KKD,KERALA,673603")
driver.find_element(by=By.NAME,value="submit").click()
driver.maximize_window()
driver.find_element(by=By.ID,value="male").click()
driver.find_element(by=By.ID,value="tuesday").click()
driver.find_element(by=By.ID,value="wednesday").click()
driver.find_element(by=By.ID,value="sunday").click()
b=driver.find_element(by=By.XPATH,value="/html/body/div/div[4]/div[2]/div/select")
c=Select(b)
c.select_by_value("4")
driver.find_element(by=By.XPATH,value="/html/body/div/div[5]/div[2]/div[1]/div[1]/label").click()
driver.find_element(by=By.XPATH,value="/html/body/div/div[5]/div[2]/div[2]/div[1]/label").click()
driver.find_element(by=By.XPATH,value="/html/body/div/div[5]/div[2]/div[2]/div[3]/label").click()
driver.find_element(by=By.XPATH,value="//*[@id='inputGroupFile02']").send_keys("C:\\Users\\conta\\OneDrive\\Desktop\\jishnu\\hloo.txt")
driver.find_element(by=By.ID,value="Upload").click()